## Question 1:
# Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.


In [11]:
import numpy as np
a=np.random.rand(10,1)
print(a)
print(a.mean())

[[0.84222326]
 [0.77567732]
 [0.73457328]
 [0.84963248]
 [0.72582683]
 [0.94387984]
 [0.6875138 ]
 [0.3598439 ]
 [0.64034667]
 [0.07488117]]
0.6634398541246453


# Question 2:

## Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [3]:
import numpy as np
a=np.random.rand(20,1)
print(a)
print(a.std())
print(a.var())

[[0.91809052]
 [0.96607809]
 [0.26159521]
 [0.44490396]
 [0.37381152]
 [0.36307476]
 [0.18056   ]
 [0.99099298]
 [0.17084176]
 [0.36045171]
 [0.6048339 ]
 [0.80399856]
 [0.23664601]
 [0.60550056]
 [0.40766261]
 [0.32375803]
 [0.7731513 ]
 [0.18752746]
 [0.56603542]
 [0.81412145]]
0.2692598171347876
0.07250084912345926


# Question3:
## Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [8]:
import numpy as np
a=np.random.rand(10,20)
b=np.random.rand(20,25)
c=np.matmul(a,b)
print(c)
print(c.sum())

[[4.09697207 5.37195204 4.5003605  4.5012108  4.09371936 4.03852789
  4.67336284 4.82467026 3.80686381 4.19281177 4.60764611 4.29198204
  5.6653181  5.17419485 4.91171171 4.84008895 4.48305364 4.03155192
  3.89658881 5.11095145 3.73228486 5.52635271 3.82803843 5.63698496
  5.41690836]
 [5.04657065 5.97861413 6.15616485 6.41410631 4.20194237 6.29022281
  6.35632398 6.52434802 5.4806049  5.62846404 5.93870306 6.88420424
  7.34356049 7.09005343 6.88184479 6.83474403 6.56909244 4.79584487
  5.07210769 7.04607408 5.13795599 8.1773783  5.44000829 7.55835259
  7.32396002]
 [3.79899884 4.45196247 4.09601124 5.59583893 4.18332743 4.37906581
  4.81934971 5.09276229 4.04202268 4.32828073 5.06091691 5.10726757
  5.65413776 5.53701162 5.3048933  5.47780433 5.05628992 3.92139241
  4.40297192 5.68129281 4.95423782 7.16470264 4.88029206 5.82080398
  5.46747901]
 [5.14452701 5.85709402 6.18228659 6.45903124 4.47701321 6.05776488
  5.57137592 6.58647534 5.92957026 5.91873228 6.4672383  6.35937171
  6.90

# Question4:
## Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 


In [25]:
import numpy as np
a=np.random.rand(10,1)
print(a)
def func(x) :
    return(1/(1+np.exp(-x)))
result=np.apply_along_axis(func, 0 , a)
print(result)
    


[[0.01472688]
 [0.24624609]
 [0.88137941]
 [0.16843796]
 [0.947478  ]
 [0.99113502]
 [0.79968254]
 [0.96826077]
 [0.18058074]
 [0.49039253]]
[[0.50368165]
 [0.56125232]
 [0.70710799]
 [0.54201021]
 [0.7206077 ]
 [0.72931205]
 [0.68990657]
 [0.7247727 ]
 [0.5450229 ]
 [0.6201989 ]]
